### ISSUE TITLE
[BUG] a post content is not changing immediately

### ISSUE THREAD

**Issue by SeolyeongBae** [gsainfoteam/ziggle-flutter#105]
### 버그 내용
다른 공지글을 눌렀을 때 이전에 본 공지글에서 내용이 바뀌지 않고 있습니다

### how to reproduce

https://github.com/gsainfoteam/ziggle-flutter/assets/80435616/b4aa5c6c-f3f2-49cf-8d6f-964601f02e85

스타디움을 누른다 -> 곧바로 뒤로가기 -> 도토릿을 누른다
도토릿의 내용이 바로 나타나지 않고 스타디움의 내용이 그대로 나타나고 있습니다.

### environment
갤럭시 S21을 사용 중이며, 지글을 최신 버전으로 업데이트했습니다.
로그인하지 않은 상태에서 사용하고 있습니다.

### 예상되는 정상 동작
게시글 A를 누르고 곧바로 뒤로가기를 한 뒤, 게시글 B를 누르면 게시글 B의 내용이 바로 나타나야 합니다.
상태 관리 라이브러리나, 로딩 속도를 줄이기 위해 내용을 캐싱하는 과정에서 문제가 발생한 게 아닌가 예상합니다.

**Comment by 2paperstar** [comment]
will be closed by resolving #88

**Comment by SeolyeongBae** [comment]
이미 해결 중이신 이슈였군요! 제가 컨텍스트를 바로바로 따라가고 있지 않아서 잘 몰랐습니다
감사합니다 👍

**Comment by 2paperstar** [comment]
> 이미 해결 중이신 이슈였군요! 제가 컨텍스트를 바로바로 따라가고 있지 않아서 잘 몰랐습니다 감사합니다 👍

사실 #88번(상태관리 라이브러리 변경)을 통해서 직접적으로 해결 되는건 아니고, 간접적으로 해결 될 이슈이긴합니다
