### ISSUE TITLE
[BUG] cannot login when after force logout

### ISSUE THREAD

**Issue by controlZ** [gsainfoteam/ziggle-flutter#107]
**구현 영상 및 사진**
https://github.com/gsainfoteam/ziggle-flutter/assets/101192718/9889686e-3441-45db-ab2a-2fba7cd335a3
![지글 앱 버그 사진](https://github.com/gsainfoteam/ziggle-flutter/assets/101192718/16313c57-c239-47f9-b33c-b4a581001cff)

**버그 내용**
제 경우에는 지글 앱에서 로그아웃 한 뒤 앱에 재로그인을 하는 경우, GSA 통합계정으로 로그인하는 링크가 열리면 위의 사진처럼 나왔습니다. 로그인 시도할 때 마다 위의 사진과 같은 상황이 발생하여 로그인이 되지않았습니다.
또 제 친구의 경우가 영상인데, 저번에 시도했을때는 되었으나 현재 글 작성을 위해 GSA 통합계정으로 로그인버튼을 눌렀으나 위의 영상처럼 뜬다고 합니다.

**Comment by 2paperstar** [comment]
https://github.com/gsainfoteam/ziggle-flutter/blob/6b9ea2dfbd2f5695883764b6784a4efaf45641d5/lib/app/core/values/strings.dart#L3-L9

재로그인 url에서 prompt 파라미터 두개 들어감

**Comment by 2paperstar** [comment]
idp 쪽에서도 문제가 있는 것 추후 확인하였습니다. https://github.com/gsainfoteam/idp-fe/commit/dd868ef6626d700dd8048f1fc374e860c2e63331 에서 수정됐습니다.
