### ISSUE TITLE
Cannot Write Notice Article

### ISSUE THREAD

**Issue by no-ikjun** [gsainfoteam/ziggle-flutter#250]
- 공지 작성 후 Done 누를 시 discard 팝업

![image](https://github.com/gsainfoteam/ziggle-flutter/assets/96350366/913c3cc6-0223-4385-91cf-254e56140d2e)

**Comment by 2paperstar** [comment]
TODO: GoRouter의 breaking change가 완전히 반영 되었는지 확인
