### ISSUE TITLE
[DESIGN] Annotated Region not applied

### ISSUE THREAD

**Issue by dawnfire05** [gsainfoteam/ziggle-flutter#277]
앱을 처음 시작했을 때 상단의 Annotated Region이 회색임.
원래는 흰색이여야 함.
Route 타고 이동하면 다시 흰색이 되긴 함.
첫 시작에서 annotated region이 잘 동작하도록 수정하기.

**Comment by 2paperstar** [comment]
#259 와 동일한 이슈인가요?

**Comment by dawnfire05** [comment]
비슷하면서도 다른 문제 같아용
#259 는 Annotated Region property에 위 아래를 따로 지정할 수 있는지 살펴봐야 할 것 같구요
본 이슈는 Annotated Region 생명주기(?) 관련 문제 아닐까 생각해염.
스플래시 화면 이후 곧바로 본 위젯이 적용되지 않는 것 같은데 이것도 살펴봐야 할 것 같습니당

**Comment by 2paperstar** [comment]
안드에서 이제 잘 되나요?! @dawnfire05

**Comment by dawnfire05** [comment]
아뇨
바꾸고 이슈 생기면 그때 다시 열려고 닫았어요

**Comment by 2paperstar** [comment]
> 아뇨 바꾸고 이슈 생기면 그때 다시 열려고 닫았어요

좋습니다!
