### ISSUE TITLE
[BUG] can't enter notice detail through alarm.

### ISSUE THREAD

**Issue by dawnfire05** [gsainfoteam/ziggle-flutter#280]
에타에 해당 문제가 이슈되었습니다.
리뉴얼 이전에 해당 문제 해결을 먼저 하는게 좋아보입니다.
@2paperstar

**Comment by 2paperstar** [comment]
#381 을 통해 해결하였습니다만, 완전히 해결 되었는지는 확인이 필요합니다

**Comment by 2paperstar** [comment]
duplicated with #129
