### ISSUE TITLE
[V4] implement widgets

### ISSUE THREAD

**Issue by 2paperstar** [gsainfoteam/ziggle-flutter#281]
- Common
    - [x] #301
        - compact: bool
        - title: string
        - actions: List<Widget>
        - leading: Widget
    - [x] #289
        - label: string
    - [x]  #287 
    - [x] #307
        - icon
        - title
        - disabled?
        - trailingIcon
    - [x] #282
        - emphasize
        - outlined
        - disabled
        - type (default: CTA)
            - cta, big, small
    - [x] #291 
    - [x] #294
    - [x] #286
        - close button, title
    - [x] #308
    - [x] #304
    - [x] #305
        - disabled
    - [x] #284
        - small
        - value
        - options
    - [x] #299
        - long
    - [x] #311
-  Notice
    - [x] #318
    - [x] #310
    - [x] #296
    - [x] #319
    - [x] #321
- Groups (생각이 필요한 것들)
    - [x] #371
    - [x] #330
    - [x] #370
    - [x]  CreationProgress
        - ProgressBar랑 같이 있는 위젯
        - Hero 사용

**Comment by dawnfire05** [comment]
Groups 기능에 왜 생각이 필요한 것들이라고 써져 있는건가염
구현된 적이 없어서 그런가요?
@2paperstar

**Comment by 2paperstar** [comment]
> Groups 기능에 왜 생각이 필요한 것들이라고 써져 있는건가염
> 
> 구현된 적이 없어서 그런가요?
> 
> @2paperstar 

속성들을 어떻게 할지 고민했던 것 같아요

**Comment by dawnfire05** [comment]
done!

**Comment by 2paperstar** [comment]
> done!

good! 수고했습니다! 이 이슈는 클로즈 하도록 할게요
