### ISSUE TITLE
[V4] lottie

### ISSUE THREAD

**Issue by 2paperstar** [gsainfoteam/ziggle-flutter#357]

**Comment by dawnfire05** [comment]
@2paperstar CircularProgressIndicator 있는 곳들 다 loading lottie로 바꿔도 무방할까요?

**Comment by 2paperstar** [comment]
> @2paperstar CircularProgressIndicator 있는 곳들 다 loading lottie로 바꿔도 무방할까요?

완전 좋아~~~
