### ISSUE TITLE
[BUG] Check ValueStream.hasValue before accessing ValueStream.value

### ISSUE THREAD

**Issue by dawnfire05** [gsainfoteam/ziggle-flutter#394]
<img width="1532" alt="image" src="https://github.com/user-attachments/assets/cf3c03b5-00b5-4531-8dbc-9ddfb9334c31">

초기 실행할 때 발생하는 이유입니다.
재시작하면 괜찮아집니다.

**Comment by 2paperstar** [comment]
https://github.com/gsainfoteam/ziggle-flutter/pull/390 이거처럼 수정하면 됩니다

**Comment by 2paperstar** [comment]
1. subject의 초기값 설정하기 (seeded factory method 사용)
2. @PostConstructor(preResolve: true)가 달린 init method만들기
